name: Create Release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.1
      - name: Set up JDK 11
        uses: actions/setup-java@v2.4.0
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Check plugin version
        run: |
          version=$(sed -n "s/^pluginVersion=\(.*\)$/\1/p" gradle.properties)
          commit_version=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=release: )[^ ]+')
          if [ "$version" != "$commit_version" ]; then
            echo "Plugin version does not match commit message"
            exit 1
          fi
          echo "commit_version=$commit_version" >> $GITHUB_ENV
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.commit_version }}
          name: ${{ env.commit_version }}
          body: ${{ github.event.head_commit.message }}
